@BASE_URL = http://localhost:3000
@userID=
@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTNmNjdmMTAyZTI1NDJjZGNhNzUxMDQiLCJpYXQiOjE3NjYwNTUxNTUsImV4cCI6MTc2NjY1OTk1NX0.8Crk6VpCQFfqUZW4D81rxoAsMqQSHokwPHSb0EcQIuM
POST {{BASE_URL}}/users
Content-Type: application/json

{
    "name": "Muskan Doe",
    "email": "muskan.doe@example.com",
    "password": "password"
}

### Get all users
GET {{BASE_URL}}/users?limit=4&search=muskan&sort=name&order=asc
Authorization: Bearer {{TOKEN}}

### Get user by id
GET {{BASE_URL}}/users/691ee5dba233ff5784b89949


### Update user by id
PATCH {{BASE_URL}}/users/691c52c7584591c3a225835e
Content-Type: application/json

{
    "email": "musu.doe@example.com"
}

### Delete user by id
DELETE {{BASE_URL}}/users/691c52c7584591c3a225835e
### User registration
POST {{BASE_URL}}/auth/register
Content-Type: application/json

{
  "name": "Sanjha chy",
  "email": "muskanchy15@example.com",
  "password": "password"
}

### User login
POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
"email": "muskanchy15@example.com",
  "password": "password"
}

###create a new trip
POST {{BASE_URL}}/trips
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "title": "Kathmandu Trip",
  "description": "Winter vacation",
  "startDate": "2025-12-01",
  "endDate": "2025-12-10",
  "destinations": ["Kathmandu", "Pokhara"],
  "budget": {
    "total": 30000,
    "expenses": [
      {
        "name": "Flight",
        "amount": 15000,
        "date": "2025-11-15"
      },
      {
        "name": "Hotel",
        "amount": 10000,
        "date": "2025-12-01"
      }
    
    ]
  }
}
### Get all trips
GET {{BASE_URL}}/trips
Authorization: Bearer {{TOKEN}}
### Get trip by id
GET {{BASE_URL}}/trips/69452879454b4bc6ec7a1b41
Authorization: Bearer {{TOKEN}}

### Update trip by id
PATCH {{BASE_URL}}/trips/693f68d102e2542cdca75107
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "title": "Updated Kathmandu Trip",
  "destinations": ["Kathmandu", "Pokhara", "Chitwan"],
  "budget": {
    "total": 35000
  }
}
###Delete expense by id
DELETE {{BASE_URL}}/trips/693f68d102e2542cdca75107/expenses/693f69e202e2542cdca7510f
Authorization: Bearer {{TOKEN}}
### Delete trip by id
DELETE {{BASE_URL}}/trips/6920f4e4f1e45c3b8c4d2a1
### Get all baggages
### Create baggage for a trip
POST {{BASE_URL}}/69452879454b4bc6ec7a1b41/baggages 
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "name": "Backpack"
 
}

### Get all baggages
GET {{BASE_URL}}/69452879454b4bc6ec7a1b41/baggages
Authorization: Bearer {{TOKEN}} 
### Get baggage by id
GET {{BASE_URL}}/baggages/
Authorization: Bearer {{TOKEN}}
### Update baggage by id
PATCH {{BASE_URL}}/69452879454b4bc6ec7a1b41/baggages/69452efd42dfbed2c37187cd
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "name": "Updated Backpack",
    "completed": true
}
### Delete baggage by id
DELETE {{BASE_URL}}/baggages/693167a3fb92065a96b056d5/

###Itenarys
### Create itenary for a trip
POST {{BASE_URL}}/69452879454b4bc6ec7a1b41/itenarys
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "title": "Day 1 in Kathmandu",
  "activities": [
    {
      "time": "10:00 AM",
      "description": "Visit Pashupatinath Temple"
    },
    {
      "time": "1:00 PM",
      "description": "Lunch at local restaurant"
    }
  ]
}




